name: ServerInformation
version: 1.1
api-version: 1.15
description: Outputs server information to the console log.
author: kubotan
softdepend: [Essentials]
main: space.gorogoro.serverinformation.ServerInformation
